Added example for multi device support
WifWaf/AT24CM01 pull request #7
Opened 2023-03-23 14:13 UTC by pravinraghul

## Test results
- Tested with two device connected in I2C bus. 
- Device address is 0x50 and 0x52.

> Writing to device 0x50
0x12, 0x34, 0x56, 0x78, 0x9a, 0xbc, 0xde, 0xf0, 
Writing to device 0x52
0x12, 0x34, 0x56, 0x78, 0x9a, 0xbc, 0xde, 0xf0, 
Reading to device 0x50
0x12, 0x34, 0x56, 0x78, 0x9a, 0xbc, 0xde, 0xf0, 
Reading to device 0x52
0x12, 0x34, 0x56, 0x78, 0x9a, 0xbc, 0xde, 0xf0,

2023-03-23 15:39 UTC, WifWaf requested changes
Thanks for doing this.

I think I confused things with regard to how the library changes affect usage.

We can use a single instance and switch between addresses with the setDeviceAddress() function.

For multiple instances, it's usually best to add an argument to the constructor of the library, and then add the addresses when instancing (e.g. eeprom_dev1(0x52). This is common in Arduino, so I'm happy to add this to the library as an alternative to setDeviceAddress().

I've added some recommended changes to the library to explain, however, I can't test the library, so if you can test it, that would be great.

2023-03-23 15:39 UTC, WifWaf commented on examples/MulDevUsage/MulDevUsage.ino
> +  eeprom_dev2.begin();
```suggestion
  eeprom.begin();
```

2023-03-23 15:51 UTC, WifWaf requested changes

2023-03-23 15:51 UTC, WifWaf commented on examples/MulDevUsage/MulDevUsage.ino
> +  read(eeprom_dev2);  // 0x52
```suggestion
  Serial.println("Writing to device 0x50");
  write(eeprom); // 0x50 (library defaults to 0x50)

  eeprom.setDeviceAddress(ATDEVADR1);
  Serial.println("Writing to device 0x52");
  write(eeprom); // 0x52
  
  eeprom.setDeviceAddress(ATDEVADR0);
  Serial.println("Reading to device 0x50");
  read(eeprom);  // 0x50
  
  eeprom.setDeviceAddress(ATDEVADR1);
  Serial.println("Reading to device 0x52");
  read(eeprom);  // 0x52
```

2023-03-23 15:51 UTC, WifWaf commented on examples/MulDevUsage/MulDevUsage.ino
> +  read(eeprom_dev2);  // 0x52
Just using the single library and switch the addresses here.

2023-03-24 01:19 UTC, pravinraghul commented on examples/MulDevUsage/MulDevUsage.ino
> +  uint8_t buffer[8] {};
A buffer array to get the data from the 'readByteArray()'

>  uint8_t buff[8] {};
  eeprom.readByteArray(0, buff, sizeof(buff));

2023-03-24 01:33 UTC, pravinraghul commented
Thanks, Using single instance will be simple and good.

I've added the changed to the example.

2023-03-24 15:30 UTC, WifWaf requested changes

2023-03-24 15:30 UTC, WifWaf commented on examples/MulDevUsage/MulDevUsage.ino
> +  uint8_t buffer[8] {};
See line 44 

 "uint8_t buffer[8] {};"
 
 I think perhaps it was left over from the previous example. :)

2023-03-26 10:03 UTC, pravinraghul commented on examples/MulDevUsage/MulDevUsage.ino
> +  uint8_t buffer[8] {};
> A buffer array to get the data from the 'readByteArray()'
> 
> >  uint8_t buff[8] {};
>   eeprom.readByteArray(0, buff, sizeof(buff));
> 

I'm not sure, how I suppose to use this readByteArray() method without a char array pointer.

Can you be more specific?

2023-03-26 17:19 UTC, WifWaf commented on examples/MulDevUsage/MulDevUsage.ino
> +  uint8_t buffer[8] {};
You have a buffer declared at line 30 which is passed to the readByteArray() function, while the buffer at line 44 is not used.

2023-03-27 01:38 UTC, pravinraghul commented on examples/MulDevUsage/MulDevUsage.ino
> +  uint8_t buffer[8] {};
Thanks @WifWaf, removed the unused variable

2023-03-27 14:19 UTC, merged